### ISSUE TITLE
Doesn't work on Raspberry PI

### ISSUE THREAD

**Issue by TheGigaQuant** [sudhakar3697/detect-usb#1]
Hello, I developed a nodejs app and it works well on Windows with NodeJS 10.15.0.
But the same thing on Raspberry Pi does nothing.
The event is never triggered when I plug a USB stick.

Do you have an idea ? Thanks

**Comment by sudhakar3697** [comment]
Sry for the delay in response.
@JulienPlanchetCoineo What OS are you running on Raspberry Pi?

**Comment by TheGigaQuant** [comment]
@sudhakar3697 I'm running Raspbian OS

**Comment by sudhakar3697** [comment]
The support for this package on Raspbian OS depends on the two modules used in this project (usb-detection & drivelist).

**Comment by TheGigaQuant** [comment]
I see, I installed libudev.h with : sudo apt-get install libudev-dev
Then, I could use npm install command and everything has compiled.
But when I start the project, nothing happens for detect-usb

**Comment by sudhakar3697** [comment]
Kindly try running the following code after connecting the USB and share the console output,

```
const usbEvents = require('detect-usb');

// To start listening
usbEvents.startListening();

// To get list of connected USBs
(async () => {
    console.log(await usbEvents.getUSBList());
})();
```

**Comment by TheGigaQuant** [comment]
Hi, thanks for your help, the function getUSBList() doesn't exists, I had to rewrite it to usbEvents.usbList;
And the results is an empty array

**Comment by TheGigaQuant** [comment]
I've found a way. It was not because of the plugin itself, it was because the USB was not clearly mounted on the Raspbian OS.. Here is how I manage to solve it :
```
sudo apt-get install usbmount
sudo nano /lib/systemd/system/systemd-udevd.service
```
Edit MountFlags=slave to MountFlags=shared
Reboot

Thanks for your help 👍
