### ISSUE TITLE
could you please update new  version.

### ISSUE THREAD

**Issue by davuttemel** [sudhakar3697/detect-usb#3]
give me version error. please update

**Comment by sudhakar3697** [comment]
Can you pls post the error here?

**Comment by davuttemel** [comment]
oh  ok.. 

etection/build/Release/detection.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 119. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by sudhakar3697** [comment]
A new version of the package detect-usb (3.0.0) was published at 2023-12-18T11:19:21.316Z from 106.197.71.91.
The shasum of this package is 20b38275cc7648c08c77b04dfe6f2e8c61163be3.

Thank you.
