### ISSUE TITLE
how can I use with electron

### ISSUE THREAD

**Issue by davuttemel** [sudhakar3697/detect-usb#4]
hi bro. I want to make an electron app. this app will list usb device and lisen insert remove event. an I want to save selected usb device info(serial, vendorid, productid) to selected usb path. help me please. 
you can show me a basic example. thanks

**Comment by sudhakar3697** [comment]
From #5 , I hope you are able to call the function in electron to get the response

**Comment by davuttemel** [comment]
I want to change your index.js file 
How? Please help me. Your module is ok. But extra give me serial number vendor id

**Comment by sudhakar3697** [comment]
Pls check #5
