### ISSUE TITLE
serial number, vendor id et?

### ISSUE THREAD

**Issue by davuttemel** [sudhakar3697/detect-usb#5]
hi. I use it with electron. but I need serial number, vendor id, product id. could you please help me?

**Comment by sudhakar3697** [comment]
Hi
You might have to use the usb-detection npm package to get vid & pid.

https://www.npmjs.com/package/usb-detection or https://www.npmjs.com/package/usb (Preferred)

Sample output mentioned in that library

```
{
	locationId: 0,
	vendorId: 5824,
	productId: 1155,
	deviceName: 'Teensy USB Serial (COM3)',
	manufacturer: 'PJRC.COM, LLC.',
	serialNumber: '',
	deviceAddress: 11
}
```

**Comment by sudhakar3697** [comment]
you can change in the index.js file by adding a callback parameter to the event and access the data which contains the vid, pid

```
 usbDetect.on('add', async (data) => {
                console.log(data)
```

The above should print something like the below,

```
{
  locationId: 0,
  vendorId: 1356,
  productId: 2500,
  deviceName: 'USB Mass Storage Device',
  manufacturer: 'Compatible USB storage device',
  serialNumber: 'BC07009379261BAE04',
  deviceAddress: 18
}
```

**Comment by davuttemel** [comment]
you module print like that.
{
    key: '/Volumes/NO NAME',
    name: 'NO NAME',
    devicepath: '/dev/disk4',
    isAccessible: true,
  }
  
i want to add 2 parameters lite that. I change your function but don't make good code..:(
{
    key: '/Volumes/NO NAME',
    name: 'NO NAME',
    devicepath: '/dev/disk4',
    isAccessible: true,
    vendorId: '34234234',
    serialNumber:'24234234234'
  }

**Comment by sudhakar3697** [comment]
> you can change in the index.js file by adding a callback parameter to the event and access the data which contains the vid, pid
> 
> ```
>  usbDetect.on('add', async (data) => {
>                 console.log(data)
> ```
> 
> The above should print something like the below,
> 
> ```
> {
>   locationId: 0,
>   vendorId: 1356,
>   productId: 2500,
>   deviceName: 'USB Mass Storage Device',
>   manufacturer: 'Compatible USB storage device',
>   serialNumber: 'BC07009379261BAE04',
>   deviceAddress: 18
> }
> ```

Did you try this change?. Are you getting vid, pid?.

**Comment by davuttemel** [comment]
thank you very much. you are right. working fine. but now I want to same thing for     
async getUSBList() {.

**Comment by davuttemel** [comment]
thank you very much. you are right. working fine. but now I want to same thing for
async getUSBList() {.

**Comment by davuttemel** [comment]
use it like that.  it it working fine.           
 ```
usbDetect.on('add', async (data) => {

const mountData = {
                                            key: i.path,
                                            name: Utils.getUSBLabel(i.path),
                                            devicepath: drive.device,
                                            isAccessible: await Utils.isReadable(i.path),
                                            vendorId:data.vendorId,
                                            productId:data.productId,

```
now I want to use same thing for     async getUSBList() method. listing device props like add callback. but how can I send data :( or may I use  usbDetect.on('change', event for it..

**Comment by davuttemel** [comment]
this will be my last question sir. please..

**Comment by davuttemel** [comment]
When I insert usb I get serial and vendorid info.  usbDetect.on('add', async (data) => {
                console.log(data)

 And I must same thing for getUsbList(). How to send async (data) to this method.

**Comment by sudhakar3697** [comment]
Sorry for the late response. The packages used in this project (usb-detection, drivelist) do not have a common field with which we can map the entries. During the add event, we just poll and find out the newly added USB with vid and pid along with the mount path.

Pls check with the https://www.npmjs.com/package/usb module (https://github.com/node-usb/node-usb)

Thank you.
